[project]
name = "llm-gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "google-genai>=2.23.0",
    "ollama>=0.6.2",
    "openrouter>=1.1.140",
    "pika>=1.4.4",
    "uvicorn>=0.53.0",
]
